import Head from "next/head";
import {Info} from "@/components/info/Info"
import styled from "styled-components"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <PageContainer>
        <Info/>
      </PageContainer>
    </>
  )
}

const PageContainer = styled.div`
  display: flex;
  flex: 1;
  width: 100%;
`
