name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
      - name: Install Node and dependencies
        uses: ./.github/actions/install-dependencies
      - run: pnpm run lint
